// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4915.ArcadeDriveRobot.subsystems;
import org.usfirst.frc4915.ArcadeDriveRobot.RobotMap;
import org.usfirst.frc4915.ArcadeDriveRobot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;
import edu.wpi.first.wpilibj.smartdashboard.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class Launcher extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Solenoid gearboxPneumatics = RobotMap.launcherGearboxPneumatics;
    SpeedController windingMotor = RobotMap.launcherWindingMotor;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    /**
     * extendPneumatics
     * 
     * Pushes the pneumatic cylinder out
     */
    public void pneumaticsOn() {
        gearboxPneumatics.set(true);
    }
  
    /**
     * stop
     * 
     * Stops filling the cylinder. Will not retract it, but will allow it to be pushed back
     */
    public void stop() {
        gearboxPneumatics.set(false);
    }
    
    /**
     * getStatePneumatics
     * 
     * @return the state of gearboxPneumatics
     */
    public boolean getStatePneumatics() {
        return gearboxPneumatics.get();
    }
      
    public void startWindingMotor(double speed){
        windingMotor.set(speed);
    }
    public void stopWindingMotor() {
        windingMotor.set(0.0);
    }
    public double getWindingSpeed() {
        return windingMotor.get();
    }
}
