// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4915.ArcadeDriveRobot.commands;
import org.usfirst.frc4915.ArcadeDriveRobot.OI;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4915.ArcadeDriveRobot.Robot;
import org.usfirst.frc4915.ArcadeDriveRobot.RobotMap;
/**
 *
 */
public class  ArcadeDrive extends Command {
    public Joystick joystickDrive = Robot.oi.getJoystickDrive();
    public double joystickThrottle = .5 * (-1 * joystickDrive.getAxis(Joystick.AxisType.kThrottle) + 1.0);
    
    public ArcadeDrive() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.driveTrain.arcadeDrive(Robot.oi.getJoystickDrive());
        

        Joystick joystickDrive = Robot.oi.getJoystickDrive();
        double joystickThrottle = .5 * (-1 * joystickDrive.getAxis(Joystick.AxisType.kThrottle) + 1.0); // Goes from 0 to 1, flipping the throttle on hardware to make sense
        Robot.driveTrain.setMaxOutput(joystickThrottle); // Advanced Joystick goes from 0 to 1
        // RobotMap.driveTrainRobotDrive.setMaxOutput(joystickDrive.getAxis(Joystick.AxisType.kZ)); // Attack Joystick
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.driveTrain.stop();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
