// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4915.ArcadeDriveRobot.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4915.ArcadeDriveRobot.Robot;
import org.usfirst.frc4915.ArcadeDriveRobot.subsystems.Harvester;
/**
 *
 */
public class IntakeUp extends Command {
    private boolean timerSet;
    private boolean shouldQuit;
    public IntakeUp() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.harvester);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        Robot.harvester.stopWheels();
        shouldQuit = false;
        if ((Robot.launcher.hasLaunchedBall() == true)) {
            shouldQuit = true;
            System.out.println("Aborting IntakeUp, launcher is up.");
        } else {
            Robot.harvester.retractPneumatics();
            timerSet = false;
            System.out.println("Starting IntakeUp...");
        }
        setTimeout(1.0);
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        if (!shouldQuit) {
            Robot.harvester.setWheelSpeed(Robot.harvester.getHarvesterSpeed(Harvester.INTAKE));
            /*if (Robot.harvester.isHarvesterUp() && (timerSet == false)) {
            setTimeout(2.0); // Keep spinning wheels after pneumatics are up to ensure ball is held properly
            timerSet = true;
            }*/
        }
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        if (shouldQuit) {
            return true;
        }
        else {
            return isTimedOut();
        }
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.harvester.stopWheels();
        System.out.println("IntakeUp done.");
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
